### ISSUE TITLE
Custom content?

### ISSUE THREAD

**Issue by tizu69** [stordahl/svelte-right-click#7]
Is there any way this could be implemented using slots, i.e. like this?
```html
<ContextMenu>
	r-click me! (only content in here will be rightclickable)
	<svelte:fragment slot="menu">
		I could put anything here. images, buttons, etc.
	</svelte:fragment>
</ContextMenu>
```

**Comment by stordahl** [comment]
There are other packages that use this pattern - I'd suggest you check them out instead of this lib

**Comment by stordahl** [comment]
More info can be found [here](https://svelte-right-click.vercel.app/docs/philosophy)
